// Post data — security writeups + personal/dev journal entries
// Tone: technical, dry, slightly mordant. Fin is a hacker; writes like one.

const POSTS = [
  {
    id: "0x06",
    slug: "openvpn-config-injection",
    title: "Burning down a corpo VPN: weaponizing OpenVPN config injection",
    kind: "WRITEUP",
    tags: ["netsec", "rce", "vpn"],
    date: "2026.05.11",
    read: "12 min",
    severity: "HIGH",
    excerpt:
      "A misconfigured ovpn distribution endpoint let me inject directives that run as root on every employee laptop. Here's how it broke, and how to stop bleeding.",
    body: [
      ["p", "Most corpo VPN clients trust the config file more than the user. That's the bug. Not a CVE, not a zero-day — just trust radiating outward from a server nobody patched since the IPO."],
      ["h3", "// The setup"],
      ["p", "The target distributes per-user ovpn profiles via an authenticated portal. Pull your profile, drop it into the client, you're on the corp net. Standard. The portal is a thin Flask app behind nginx; the profile is templated from a Jinja2 string that interpolates the username into the X.509 subject and a routing block."],
      ["p", "The username field accepts newlines. The template doesn't escape them. OpenVPN's config parser treats every line as a directive."],
      ["code", "POST /profile/generate\nusername=fin%0Ascript-security%202%0Aup%20/tmp/x.sh%0A"],
      ["h3", "// The payload"],
      ["p", "OpenVPN runs the `up` script as root by default on Linux clients. The `script-security 2` directive enables user-supplied scripts. Two extra lines in the profile and every laptop that imports it executes my code at connect time."],
      ["p", "Persistence is trivial: drop a launchd plist on macOS, a systemd unit on Linux, a scheduled task on Windows. The VPN client doesn't care. The user clicked Connect."],
      ["h3", "// The fix"],
      ["p", "Strip control characters from every templated input. Treat config generation like SQL: parameterize, don't concatenate. Set `script-security 0` in a server-pushed config and refuse profiles that try to raise it. Sign your ovpn files and verify on import."],
      ["p", "I disclosed Tuesday. Patch shipped Thursday. They paid the bounty in crypto, which is the kind of cyberpunk detail I'd put in a story if it didn't happen so often."],
    ],
  },
  {
    id: "0x05",
    slug: "analog-notes",
    title: "On staying analog: why I still take handwritten notes",
    kind: "JOURNAL",
    tags: ["personal", "tools"],
    date: "2026.05.04",
    read: "5 min",
    severity: null,
    excerpt:
      "Every productivity app I've tried wants to be a database. I don't need a database. I need a place to think slowly.",
    body: [
      ["p", "I keep a paper notebook. Field Notes, the boring kraft ones, three to a pack. I burn through one every six weeks or so. They live in a stack on the shelf above my desk, dated on the spine in silver Sharpie."],
      ["p", "People ask me why. The honest answer is that I trust my hands more than I trust software."],
      ["h3", "// What the notebook is for"],
      ["p", "Anything I want to actually remember. Architecture sketches. The shape of an exploit before I write the code. Phone numbers. Lock combinations I shouldn't be writing down. The first three lines of a poem that won't leave me alone."],
      ["p", "Anything I want to think about slowly. Pen forces a rate limit. You can't autocomplete a thought in cursive."],
      ["h3", "// What it isn't for"],
      ["p", "Anything searchable. Anything I need to share. Anything that benefits from being copy-pasted. For those I use plain text files in a flat folder, synced over Syncthing, edited in nvim. No app, no graph view, no AI assistant. The folder is the database."],
      ["p", "The notebooks aren't precious. I'm not building a system. I'm just writing things down. When the current one fills up I start a new one, and the old one goes on the shelf, and I almost never open it again. That's fine. The point was the writing, not the reading."],
    ],
  },
  {
    id: "0x04",
    slug: "secure-chat-firmware",
    title: "Reversing a 'secure' chat app firmware in four hours",
    kind: "WRITEUP",
    tags: ["reversing", "crypto", "iot"],
    date: "2026.04.22",
    read: "18 min",
    severity: "CRITICAL",
    excerpt:
      "Marketed as end-to-end encrypted. Was, technically. The key derivation was deterministic from the device serial.",
    body: [
      ["p", "I won't name the vendor because the lawyers and I have an understanding. Call it Vendor X. They sell a $400 hardware chat 'pager' to people who think Signal is for civilians."],
      ["h3", "// Pulling the firmware"],
      ["p", "UART pads on the back of the board, unmarked but obvious. 115200 baud, U-Boot drops to a shell if you mash the spacebar during boot. From there, `md.l` and a serial capture script gets you the entire flash in about an hour. The bootloader doesn't verify image signatures, which is the first sign you're going to have a good day."],
      ["h3", "// The key schedule"],
      ["p", "The 'E2E' protocol is a custom thing built on top of libsodium. libsodium is fine. The custom thing is not."],
      ["code", "key = HKDF(\n  ikm  = SERIAL || FIRMWARE_VERSION,\n  salt = 0x00 * 32,\n  info = \"chat-session-v1\"\n)"],
      ["p", "The serial is printed on the back of the device. The firmware version is in every protocol handshake, unencrypted. The salt is zero. The key derivation has no contribution from either party's identity, no Diffie-Hellman, no ratchet, nothing."],
      ["p", "Given a serial number — which you can read across the room with a long lens — you can decrypt every message that device has ever sent or received."],
      ["h3", "// Disclosure"],
      ["p", "Vendor X's first response was a cease and desist. Their second response, after I sent the PoC to a journalist I trust, was a firmware update and a settlement with an NDA I didn't sign. The product still ships. The marketing page still says E2E. The serial is still printed on the back."],
    ],
  },
  {
    id: "0x03",
    slug: "week-in-tmux",
    title: "The week I lived in tmux",
    kind: "JOURNAL",
    tags: ["dev", "tools", "experiment"],
    date: "2026.04.10",
    read: "7 min",
    severity: null,
    excerpt:
      "An experiment: no GUI apps for seven days. Just a terminal, a window manager, and stubbornness. Here's what broke.",
    body: [
      ["p", "I do this every couple years. Strip everything back to text. See what I actually need versus what I've accumulated. This time I went a step further and lived entirely inside a single tmux session for a week."],
      ["h3", "// The setup"],
      ["p", "i3 as the WM but only one workspace, with a single full-screen alacritty. Inside it, tmux. Inside tmux, everything: nvim for code, w3m for the web, mutt for email, ncmpcpp for music, weechat for IRC, btop for the panic attacks."],
      ["h3", "// What worked"],
      ["p", "Email got faster. Way faster. Mutt's keybinds are muscle memory after about two days and the lack of a unified inbox view forced me to actually triage. Code review in nvim with a diff buffer is better than any web UI. IRC has been good for thirty years and remains good."],
      ["h3", "// What broke"],
      ["p", "Anything with a map. Anything with a video. The bank. Signal desktop, which I'd forgotten I depend on. PDFs with figures, which is most PDFs worth reading. A Zoom call I had to take from my phone in the kitchen."],
      ["p", "Also: I missed images more than I expected. Not memes — diagrams. A good architecture diagram does in two seconds what three paragraphs of ASCII art can't."],
      ["h3", "// What I kept"],
      ["p", "Mutt is back permanently. Nvim never left. I dropped my code editor's GUI for good. Everything else returned to its previous state and I'm okay with that. The point of these experiments isn't to live ascetically — it's to find out which tools I'd actually miss."],
    ],
  },
  {
    id: "0x02",
    slug: "dns-rebinding-returns",
    title: "DNS rebinding is back, and it's wearing a hoodie",
    kind: "WRITEUP",
    tags: ["netsec", "web", "dns"],
    date: "2026.03.28",
    read: "9 min",
    severity: "MEDIUM",
    excerpt:
      "Local-network IoT dashboards keep reinventing the same mistake. A short tour of why your smart fridge is one malicious ad away from a botnet.",
    body: [
      ["p", "DNS rebinding isn't new. It's been documented since 2007. It keeps working because the people shipping local-network web UIs aren't reading 2007 papers."],
      ["h3", "// The attack, in three steps"],
      ["p", "One. Victim visits attacker.com. Two. attacker.com resolves to attacker's real IP, serves a page with JavaScript, then changes its DNS record to point at 192.168.1.1 with a short TTL. Three. The JavaScript, now considered same-origin with the victim's router admin panel, posts whatever it wants to whatever endpoint it likes."],
      ["h3", "// Why it still works"],
      ["p", "Every cheap smart-home device ships a local web UI. Most of those UIs don't check the Host header. Most of them have no CSRF protection because the developers assume nobody can reach them from the outside. The whole threat model is 'the LAN is friendly,' which stopped being true around the time the Roomba grew a microphone."],
      ["h3", "// Defenses"],
      ["p", "Validate the Host header. Reject anything that isn't an IP or a hostname you control. Add CSRF tokens even on a LAN UI. Require auth for state-changing endpoints, even on a LAN UI. Use HTTPS with a self-signed cert; the browser warning is a feature here, not a bug."],
      ["p", "None of this is hard. It's just unglamorous. Which is why, in 2026, I'm still writing this post."],
    ],
  },
  {
    id: "0x01",
    slug: "three-years-out",
    title: "Three years since I quit the corp job",
    kind: "JOURNAL",
    tags: ["personal", "freelance"],
    date: "2026.03.15",
    read: "6 min",
    severity: null,
    excerpt:
      "What I thought freelance security work would be, versus what it actually is. Mostly: more invoicing, less Mr. Robot.",
    body: [
      ["p", "Three years ago today I sent a calendar invite called 'quick chat' to my skip-level and resigned thirty minutes later. I had four months of runway and one signed contract. I felt indestructible. I was, in retrospect, mostly tired."],
      ["h3", "// What I expected"],
      ["p", "More technical work. Bigger targets. The freedom to go deep on a single bug for weeks. A vague sense that I'd finally be doing the 'real' version of what I'd been hired to do at the corp."],
      ["h3", "// What I got"],
      ["p", "Roughly forty percent of my time is invoicing, scoping, and email. Another thirty is writing reports nobody enjoys reading. Twenty is the actual work. The last ten is the weird overhead of being a one-person business — taxes, insurance, the dentist asking who my employer is."],
      ["p", "The work itself is better. The targets are smaller but more interesting. I get to say no, which is the single biggest upgrade nobody talks about. I said no to a contract last month because I didn't like how the client talked about their users. That option didn't exist when I had a manager."],
      ["h3", "// The honest part"],
      ["p", "I make less money. Not a lot less, but less. I work fewer hours but I think about work more. The line between weekend and weekday is gone and I haven't decided whether that's a feature."],
      ["p", "Would I go back? No. But I won't pretend it's a Mr. Robot fantasy out here. Mostly it's me, this desk, the notebook on the shelf, and the next contract."],
    ],
  },
];

window.POSTS = POSTS;
